(
SELECT first_name,last_name FROM customer
)
UNION ALL
(
SELECT first_name,last_name FROM actor
);
--JOINED FIRST NAME AND LAST NAME COLUMNS FROM ACTOR AND CUSTOMER TABLE AND LISTED

(
SELECT first_name,last_name FROM customer
)
INTERSECT
(
SELECT first_name,last_name FROM actor
);
--JOINED FIRST AND LAST NAME COLUMNS FROM ACTOR AND CUSTOMER TABLE AND LISTED INTERSECTION OF THEM

(
SELECT first_name,last_name FROM actor
)
EXCEPT 
(
SELECT first_name,last_name FROM customer
);
--LISTED ROWS WHICH ARE VALID FOR FIRST EXPRESSION BUT NOT FOR THE SECOND EXPRESSION

--YOU CAN USE ALL 'ALL' WORD AFTER EXCEPT,INTERSECT AND UNION THIS WAY YOU CAN GET THE ROWS WHICH ARE 
--IDENTICAL
